### ISSUE TITLE
Not working the code.

### ISSUE THREAD

**Issue by seominseok0429** [Valkyrja3607/TAG#1]
hello.

First of all, thank you so much for your amazing wok.

But your code doesn't work.

Below is the error.

thank you

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/b5a4504d-759d-48c7-b71c-4cf90949b7ca">

**Comment by Valkyrja3607** [comment]
Thank you for your interest. 

I realized I forgot to include the requirements.txt, so I've added it now. I believe everything should work correctly if you run `make build` and `make run`.
